[package]
edition = "2021"
name = "kafka-crab-js"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4", "tokio_rt"] }
napi-derive = "2.12.2"
tracing = "0.1"
anyhow = { version= "1.0", features = ["backtrace"]}
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rdkafka = { version = "0.31", features = ["libz-static", "cmake-build", "tokio", "ssl-vendored"] }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
